---
wine:
    build: ./
    environment:
        - VIRTUAL_HOST=cellar.justbuchanan.com
        - LETSENCRYPT_EMAIL=justbuchanan@gmail.com
        - LETSENCRYPT_HOST=cellar.justbuchanan.com
    volumes:
      - /home/justin/cellar-data/cellar.sqlite3db:/data/cellar.sqlite3db
      - ./cellar-config.json:/etc/cellar-config.json:ro
